package com.penglab.hi5.core.ui.annotation;

public enum EditMode {
    NONE, ZOOM, PINPOINT, PAINT_CURVE, DELETE_MARKER, DELETE_CURVE, SPLIT, CHANGE_MARKER_TYPE, CHANGE_CURVE_TYPE, DELETE_MULTI_MARKER, ZOOM_IN_ROI
}
